# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demo.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1400, 900)
        Form.setFixedSize(1400, 900)
        Form.setWindowFlags(Qt.FramelessWindowHint)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(30)
        Form.setFont(font)
        
        self.graphicsView_1 = QtWidgets.QGraphicsView(Form)
        self.graphicsView_1.setGeometry(QtCore.QRect(40, 20, 644, 484))
        self.graphicsView_1.setObjectName("graphicsView_1")
        self.graphicsView_2 = QtWidgets.QGraphicsView(Form)
        self.graphicsView_2.setGeometry(QtCore.QRect(720, 20, 640, 480))
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.label_1 = QtWidgets.QLabel(Form)
        self.label_1.setGeometry(QtCore.QRect(340, 510, 50, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.label_1.setFont(font)
        self.label_1.setObjectName("label_1")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(1030, 510, 50, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        
        self.textBrowser_1 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_1.setGeometry(QtCore.QRect(720, 550, 641, 71))
        self.textBrowser_1.setObjectName("textBrowser_1")
        self.textBrowser_1.setStyleSheet("font-size:20px;")

        self.pushButton_1 = QtWidgets.QPushButton(Form)
        self.pushButton_1.setGeometry(QtCore.QRect(270, 640, 160, 60))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.pushButton_1.setFont(font)
        self.pushButton_1.setObjectName("pushButton_1")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(70, 640, 140, 70))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(70, 730, 100, 60))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.pushButton_5 = QtWidgets.QPushButton(Form)
        self.pushButton_5.setGeometry(QtCore.QRect(270, 730, 160, 60))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(Form)
        self.pushButton_6.setGeometry(QtCore.QRect(470, 730, 160, 60))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(470, 640, 160, 60))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(670, 640, 160, 60))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setGeometry(QtCore.QRect(1070, 640, 160, 60))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.radioButton_2 = QtWidgets.QRadioButton(Form)
        self.radioButton_2.setGeometry(QtCore.QRect(410, 550, 91, 71))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.radioButton_2.setFont(font)
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_1 = QtWidgets.QRadioButton(Form)
        self.radioButton_1.setGeometry(QtCore.QRect(280, 550, 91, 71))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.radioButton_1.setFont(font)
        self.radioButton_1.setMouseTracking(True)
        self.radioButton_1.setTabletTracking(False)
        self.radioButton_1.setObjectName("radioButton_1")
        self.radioButton_1.setChecked(True)
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(70, 550, 181, 70))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(70, 820, 191, 60))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.pushButton_7 = QtWidgets.QPushButton(Form)
        self.pushButton_7.setGeometry(QtCore.QRect(270, 820, 100, 60))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.pushButton_7.setFont(font)
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(Form)
        self.pushButton_8.setGeometry(QtCore.QRect(390, 820, 100, 60))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.pushButton_8.setFont(font)
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_10 = QtWidgets.QPushButton(Form)
        self.pushButton_10.setGeometry(QtCore.QRect(860, 820, 100, 60))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.pushButton_10.setFont(font)
        self.pushButton_10.setObjectName("pushButton_10")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(510, 820, 211, 60))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.pushButton_9 = QtWidgets.QPushButton(Form)
        self.pushButton_9.setGeometry(QtCore.QRect(740, 820, 100, 60))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.pushButton_9.setFont(font)
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_12 = QtWidgets.QPushButton(Form)
        self.pushButton_12.setGeometry(QtCore.QRect(1220, 820, 100, 60))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.pushButton_12.setFont(font)
        self.pushButton_12.setObjectName("pushButton_12")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(980, 820, 111, 60))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.pushButton_11 = QtWidgets.QPushButton(Form)
        self.pushButton_11.setGeometry(QtCore.QRect(1100, 820, 100, 60))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.pushButton_11.setFont(font)
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_13 = QtWidgets.QPushButton(Form)
        self.pushButton_13.setGeometry(QtCore.QRect(870, 640, 160, 60))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.pushButton_13.setFont(font)
        self.pushButton_13.setObjectName("pushButton_13")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_1.setText(_translate("Form", "IR"))
        self.label_2.setText(_translate("Form", "VI"))
        self.pushButton_1.setText(_translate("Form", "start"))
        self.label_3.setText(_translate("Form", "control"))
        self.label_4.setText(_translate("Form", "focus"))
        self.pushButton_5.setText(_translate("Form", "further"))
        self.pushButton_6.setText(_translate("Form", "closer"))
        self.pushButton_2.setText(_translate("Form", "stop"))
        self.pushButton_3.setText(_translate("Form", "save"))
        self.pushButton_4.setText(_translate("Form", "exit"))
        self.radioButton_2.setText(_translate("Form", "raw"))
        self.radioButton_1.setText(_translate("Form", "png"))
        self.label_5.setText(_translate("Form", "IR format"))
        self.label_6.setText(_translate("Form", "auto NUC"))
        self.pushButton_7.setText(_translate("Form", "on"))
        self.pushButton_8.setText(_translate("Form", "off"))
        self.pushButton_10.setText(_translate("Form", "off"))
        self.label_7.setText(_translate("Form", "noise reduce"))
        self.pushButton_9.setText(_translate("Form", "on"))
        self.pushButton_12.setText(_translate("Form", "off"))
        self.label_8.setText(_translate("Form", "adjust"))
        self.pushButton_11.setText(_translate("Form", "on"))
        self.pushButton_13.setText(_translate("Form", "record"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
